// The OpenNext worker is generated by `npm run cf-build`, so it does not exist
// in a fresh checkout before the build step.
// @ts-expect-error -- generated module intentionally resolved only during the Cloudflare build
import handler from './.open-next/worker.js';
import {
  isEmailQueueMessage,
  markEmailOutboxEnqueued,
  processEmailOutboxMessage,
  recoverPendingEmailOutbox,
  type EmailQueueMessage,
  type EmailWorkerEnv,
} from './src/lib/email-outbox';
import type {
  ExecutionContext,
  ExportedHandler,
  MessageBatch,
  ScheduledController,
} from '@cloudflare/workers-types';

export default {
  fetch: handler.fetch,

  async queue(
    batch: MessageBatch<EmailQueueMessage>,
    env: EmailWorkerEnv
  ): Promise<void> {
    for (const message of batch.messages) {
      if (!isEmailQueueMessage(message.body)) {
        console.error(JSON.stringify({ event: 'email_queue_invalid_message', messageId: message.id }));
        message.ack();
        continue;
      }

      try {
        const outcome = await processEmailOutboxMessage(env.DB, message.body);
        if (outcome.action === 'ack') {
          message.ack();
          continue;
        }

        // Publish a fresh delayed message so long quota outages are not limited
        // by the original Queue message's retention age. D1 dedupes every retry.
        try {
          await env.EMAIL_QUEUE.send(message.body, { delaySeconds: outcome.delaySeconds });
          await markEmailOutboxEnqueued(env.DB, message.body.outboxId);
          message.ack();
        } catch (error) {
          console.error(
            JSON.stringify({
              event: 'email_queue_reschedule_failed',
              outboxId: message.body.outboxId,
              error: error instanceof Error ? error.message : String(error),
            })
          );
          message.retry({ delaySeconds: outcome.delaySeconds });
        }
      } catch (error) {
        console.error(
          JSON.stringify({
            event: 'email_queue_consumer_error',
            outboxId: message.body.outboxId,
            error: error instanceof Error ? error.message : String(error),
          })
        );
        message.retry({ delaySeconds: 300 });
      }
    }
  },

  async scheduled(
    _controller: ScheduledController,
    env: EmailWorkerEnv,
    ctx: ExecutionContext
  ): Promise<void> {
    ctx.waitUntil(
      recoverPendingEmailOutbox(env.DB, env.EMAIL_QUEUE)
        .then((published) => {
          console.log(JSON.stringify({ event: 'email_outbox_recovery_complete', published }));
        })
        .catch((error) => {
          console.error(
            JSON.stringify({
              event: 'email_outbox_recovery_failed',
              error: error instanceof Error ? error.message : String(error),
            })
          );
        })
    );
  },
} satisfies ExportedHandler<EmailWorkerEnv, EmailQueueMessage>;
