// The OpenNext worker is generated by `npm run cf-build`, so it does not exist
// in a fresh checkout before the build step.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- generated module is absent before build
// @ts-ignore -- generated module intentionally resolved only during the Cloudflare build
import handler from './.open-next/worker.js';
import {
  isEmailQueueMessage,
  markEmailOutboxEnqueued,
  processEmailOutboxMessage,
  recoverPendingEmailOutbox,
  type EmailQueueMessage,
  type EmailWorkerEnv,
} from './src/lib/email-outbox';
import type {
  ExecutionContext,
  ExportedHandler,
  MessageBatch,
  ScheduledController,
} from '@cloudflare/workers-types';
import { recoverPendingPaymentAttempts } from './src/lib/payment-attempts';
import { executeSquarePaymentRequest } from './src/lib/square';
import { createOrderFromSession } from './src/lib/order-service';

type WorkerEnv = EmailWorkerEnv & Pick<WorkerBindings,
  'SQUARE_ENVIRONMENT' | 'NEXT_PUBLIC_SQUARE_LOCATION_ID' | 'NEXT_PUBLIC_SQUARE_APP_ID' | 'EMAIL_PROVIDER'
> & Partial<Pick<WorkerBindings, 'FROM_EMAIL' | 'SANDBOX_EMAIL_RECIPIENT' | 'SANDBOX_EMAIL_TEST_RECIPIENT' | 'EMAIL'>> & {
  // Secret bindings are provisioned independently of the non-secret config.
  SQUARE_ACCESS_TOKEN: string;
  RESEND_API_KEY?: string;
};

export default {
  fetch: handler.fetch,

  async queue(
    batch: MessageBatch<EmailQueueMessage>,
    env: WorkerEnv
  ): Promise<void> {
    for (const message of batch.messages) {
      if (!isEmailQueueMessage(message.body)) {
        console.error(JSON.stringify({ event: 'email_queue_invalid_message', messageId: message.id }));
        message.ack();
        continue;
      }

      try {
        const outcome = await processEmailOutboxMessage(env.DB, message.body, {
          provider: env.EMAIL_PROVIDER === 'cloudflare' ? 'cloudflare' : 'resend',
          apiKey: env.RESEND_API_KEY,
          emailBinding: env.EMAIL,
          fromEmail: env.FROM_EMAIL,
          environment: env.SQUARE_ENVIRONMENT,
          sandboxRecipient: env.SANDBOX_EMAIL_RECIPIENT,
          sandboxTestRecipient: env.SANDBOX_EMAIL_TEST_RECIPIENT,
        });
        if (outcome.action === 'ack') {
          message.ack();
          continue;
        }

        // Publish a fresh delayed message so long quota outages are not limited
        // by the original Queue message's retention age. D1 dedupes every retry.
        try {
          await env.EMAIL_QUEUE.send(message.body, { delaySeconds: outcome.delaySeconds });
          await markEmailOutboxEnqueued(env.DB, message.body.outboxId);
          message.ack();
        } catch (error) {
          console.error(
            JSON.stringify({
              event: 'email_queue_reschedule_failed',
              outboxId: message.body.outboxId,
              error: error instanceof Error ? error.message : String(error),
            })
          );
          message.retry({ delaySeconds: outcome.delaySeconds });
        }
      } catch (error) {
        console.error(
          JSON.stringify({
            event: 'email_queue_consumer_error',
            outboxId: message.body.outboxId,
            error: error instanceof Error ? error.message : String(error),
          })
        );
        message.retry({ delaySeconds: 300 });
      }
    }
  },

  async scheduled(
    _controller: ScheduledController,
    env: WorkerEnv,
    ctx: ExecutionContext
  ): Promise<void> {
    ctx.waitUntil(
      recoverPendingEmailOutbox(env.DB, env.EMAIL_QUEUE)
        .then((published) => {
          console.log(JSON.stringify({ event: 'email_outbox_recovery_complete', published }));
        })
        .catch((error) => {
          console.error(
            JSON.stringify({
              event: 'email_outbox_recovery_failed',
              error: error instanceof Error ? error.message : String(error),
            })
          );
        })
    );
    // Only previously persisted attempts are eligible. Unknown charges reuse
    // their original request/key; confirmed payments repair order persistence.
    ctx.waitUntil(
      recoverPendingPaymentAttempts(env.DB, {
        execute: (request) => executeSquarePaymentRequest(request, {
          SQUARE_ACCESS_TOKEN: env.SQUARE_ACCESS_TOKEN,
          SQUARE_ENVIRONMENT: env.SQUARE_ENVIRONMENT,
          NEXT_PUBLIC_SQUARE_LOCATION_ID: env.NEXT_PUBLIC_SQUARE_LOCATION_ID,
          NEXT_PUBLIC_SQUARE_APP_ID: env.NEXT_PUBLIC_SQUARE_APP_ID,
        }),
        finalize: (db, session, paymentId) => createOrderFromSession(
          db, session, paymentId, { emailQueue: env.EMAIL_QUEUE }
        ),
      }).then((resolved) => {
        console.log(JSON.stringify({ event: 'payment_recovery_complete', resolved }));
      }).catch(() => {
        console.error(JSON.stringify({ event: 'payment_recovery_failed' }));
      })
    );
  },
} satisfies ExportedHandler<WorkerEnv, EmailQueueMessage>;
