/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerBindings src/types/worker-bindings.d.ts` (hash: c006f0d87211a59532ff5ddda96aa39d)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	EMAIL: SendEmail;
	EMAIL_QUEUE: Queue;
	ASSETS: Fetcher;
	SQUARE_ENVIRONMENT: string;
	NEXT_PUBLIC_SQUARE_ENVIRONMENT: string;
	NEXT_PUBLIC_SQUARE_APP_ID: string;
	NEXT_PUBLIC_SQUARE_LOCATION_ID: string;
	SQUARE_WEBHOOK_URL: string;
	OWNER_NOTIFICATION_EMAIL: string;
	FROM_EMAIL: string;
	EMAIL_PROVIDER: string;
	SANDBOX_EMAIL_RECIPIENT?: string;
	SANDBOX_EMAIL_TEST_RECIPIENT?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../../custom-worker");
	}
	interface SandboxEnv {
		DB: D1Database;
		EMAIL: SendEmail;
		EMAIL_QUEUE: Queue;
		ASSETS: Fetcher;
		SQUARE_ENVIRONMENT: string;
		NEXT_PUBLIC_SQUARE_ENVIRONMENT: string;
		NEXT_PUBLIC_SQUARE_APP_ID: string;
		NEXT_PUBLIC_SQUARE_LOCATION_ID: string;
		SQUARE_WEBHOOK_URL: string;
		OWNER_NOTIFICATION_EMAIL: string;
		FROM_EMAIL: string;
		EMAIL_PROVIDER: string;
		SANDBOX_EMAIL_RECIPIENT: string;
		SANDBOX_EMAIL_TEST_RECIPIENT: string;
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SQUARE_ENVIRONMENT" | "NEXT_PUBLIC_SQUARE_ENVIRONMENT" | "NEXT_PUBLIC_SQUARE_APP_ID" | "NEXT_PUBLIC_SQUARE_LOCATION_ID" | "SQUARE_WEBHOOK_URL" | "OWNER_NOTIFICATION_EMAIL" | "FROM_EMAIL" | "EMAIL_PROVIDER" | "SANDBOX_EMAIL_RECIPIENT" | "SANDBOX_EMAIL_TEST_RECIPIENT">> {}
}
