import type { Metadata } from 'next';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import WhatsAppButton from '@/components/layout/WhatsAppButton';
import '@/styles/globals.css';

export const metadata: Metadata = {
  metadataBase: new URL('https://amammajaadi.com'),
  title: {
    default: 'Amamma Jaadi — Authentic South Indian Sweets & Pickles | Dallas, TX',
    template: '%s | Amamma Jaadi',
  },
  description:
    'Premium South Indian sweets, pickles & gift boxes in Dallas, Texas. Freshly baked daily with pure ghee, A2 milk & organic ingredients. Order Bobbatlu, Kaju Katli, Malai Khaja & more.',
  keywords: [
    'South Indian sweets Dallas',
    'Authentic Indian sweets Texas',
    'Fresh Bobbatlu Dallas',
    'Andhra sweets USA',
    'Telugu sweets Texas',
    'Indian sweets delivery Dallas',
    'Kaju Katli Dallas',
    'Malai Khaja Texas',
    'Indian pickles Dallas',
    'NRI sweets USA',
  ],
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://amammajaadi.com',
    siteName: 'Amamma Jaadi',
    title: 'Amamma Jaadi — Flavors of Home',
    description:
      'Traditional South Indian sweets made with love, just like your grandmother made them. Order fresh sweets, pickles & premium gift boxes in Dallas, TX.',
    images: [{ url: '/images/brand/logo.png', width: 512, height: 512, alt: 'Amamma Jaadi' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Amamma Jaadi — Authentic South Indian Sweets',
    description: 'Freshly baked traditional sweets & pickles delivered in Dallas, TX.',
  },
  robots: { index: true, follow: true },
  alternates: { canonical: 'https://amammajaadi.com' },
};

import { getLocalBusinessSchema } from '@/lib/seo';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Favicon is auto-generated by Next.js from src/app/icon.png & apple-icon.png */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(getLocalBusinessSchema()),
          }}
        />
      </head>
      <body className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
        <WhatsAppButton />
      </body>
    </html>
  );
}
